package com.kenymylankca.harshenuniverse.tileentity;

import kenymylankca.harshenuniverse.base.BaseTileEntityHarshenSingleItemInventory;

public class TileEntityHarshenDisplayBlock extends BaseTileEntityHarshenSingleItemInventory
{
}