package kenijey.harshenuniverse.tileentity;

import kenijey.harshenuniverse.base.BaseTileEntityHarshenSingleItemInventory;

public class TileEntityHarshenDisplayBlock extends BaseTileEntityHarshenSingleItemInventory
{
}